// src/components/Card.vue
<template>
  <!-- tags that are visible only when the preview is opened -->
  <div class="bg-in-preview" :class="{ active: open }">
    <i
      class="close x fas fa-times"
      :class="{ active: open }"
      @click="open = false"
    ></i>
    <div class="wrap-texts-in-prev" :class="{ active: open }">
      <h1 class="name-in-preview">
        {{ obj.title ? obj.title : obj.name }}
      </h1>
      <div class="stars" :class="{ active: open }">
        <i
          v-for="(n, i) in Math.ceil(
            obj.vote_average ? obj.vote_average / 2 : 0,
          )"
          :key="i"
          class="fas fa-star"
        ></i>
        <i
          v-for="(n, i) in 5 -
          Math.ceil(obj.vote_average ? obj.vote_average / 2 : 0)"
          :key="`_${i}`"
          class="far fa-star"
        ></i>
      </div>
      <p class="overview">
        {{ clipLongText(obj.overview) }}
      </p>
      <p class="releaseDate">release date: {{ obj.release_date }}</p>
      <div class="original-lang" :class="{ active: open }">
        <span>Original lenguage:</span>
        <img
          class="flag"
          v-if="flags.includes(obj.original_language)"
          :src="require(`@/assets/img/${obj.original_language}.png`)"
          :alt="`${obj.original_language} flag`"
        />
        <span v-else>{{ obj.original_language }}</span>
      </div>
      <button
        class="btn play"
        @click="
          getData(obj.id, obj.title);
          showVideo = !showVideo;
        "
      >
        <i class="fas fa-play"></i>
      </button>
      <h3
        class="add-to-favourites"
        @click="
          obj.favourite = !obj.favourite;
          pushFavuriteObj(obj);
        "
        v-show="!obj.favourite"
      >
        <i class="fas fa-plus"></i> Add to favourites list
      </h3>
      <h3
        class="remove add-to-favourites"
        @click="
          obj.favourite = !obj.favourite;
          removeFavuriteObj(obj);
        "
        v-show="obj.favourite"
      >
        <i class="fas fa-minus"></i> Remove from favourites list
      </h3>
      <VideoComp
        v-if="showVideo"
        :keyFromApi="trailerKey"
        :obj="obj"
      ></VideoComp>
    </div>
    <!-- end of tags visible only when the preview is open -->
    <a class="card" :class="{ active: open }" @click="open = true" href="#">
      <div class="poster" :class="{ active: open }">
        <div class="img-wrap" :class="{ active: open }">
          <!-- For the presentation, a background
           image was needed in a container to achieve
           the box-shadow effect in the opposite direction 
           (INSET), typical of Netflix previews -->
          <div
            v-if="obj.poster_path"
            class="img-big"
            :class="{ active: open }"
            :style="`background-image: url(https://image.tmdb.org/t/p/w342${obj.poster_path})`"
          ></div>
          <!-- placeoholder in prview when img missing -->
          <div
            v-else
            class="img-big place holder"
            :class="{ active: open }"
            :style="{
              backgroundImage:
                'url(' + require('@/assets/img/bigBrand.webp') + ')',
            }"
          ></div>
          <img
            v-if="obj.poster_path"
            :class="{ active: open }"
            :src="`https://image.tmdb.org/t/p/w342${obj.poster_path}`"
            :alt="`${obj.title ? obj.title : obj.name} sign poster`"
          />
          <!-- Placeholder when the image is missing -->
          <img
            v-else
            :class="{ active: open }"
            :src="require('@/assets/img/bigBrand.webp')"
            :alt="`${obj.title ? obj.title : obj.name} sign poster`"
          />
        </div>
        <p class="name" :class="{ active: open }">
          {{
            obj.title ? clipLongText(obj.title, 2) : clipLongText(obj.name, 2)
          }}
        </p>
      </div>
    </a>
  </div>
</template>

<script>
import * as U from '../utils';
import { mapState, mapMutations } from 'vuex';
import { getTrailerVideos } from '../features/auth/api/tmdbApi';
import VideoComp from './VideoComp.vue';

export default {
  name: 'Card',
  props: {
    obj: Object,
  },
  components: {
    VideoComp,
  },
  data() {
    return {
      trailerKey: '',
      open: false,
      showVideo: false,
    };
  },
  computed: {
    ...mapState(['flags']),
  },
  methods: {
    ...mapMutations(['pushFavuriteObj', 'removeFavuriteObj']),
    // *****
    async getData(id, isMovie) {
      try {
        const response = await getTrailerVideos({ id, isMovie });

        if (response.data.results.length > 0) {
          this.trailerKey = response.data.results[0].key;
        }
      } catch (error) {
        console.error('Error fetching video data:', error);
      }
    },
    clipLongText(str, n) {
      return U.clipLongText(str, n);
    },
  },
};
</script>

<style scoped lang="scss">
/* parcials */
@import '@/scss/var';
@import '@/scss/reset';
@import '@/scss/mixins';

.bg-in-preview {
  @media (max-width: 800px) {
    height: 200px;
  }
}

.card {
  cursor: pointer;
  min-width: 250px;
  height: 400px;
  padding: 0;
  margin: 0;
  margin-right: 30px;

  @media (max-width: 800px) {
    min-width: unset;
    height: unset;
  }

  .img-big {
    @media (max-width: 800px) {
      width: 100%;
      height: 100%;
    }
  }

  .img-wrap {
    height: 350px;
    width: 100%;
    margin-bottom: 15px;
    transition: transform 0.3s;
    &.active {
      overflow: hidden;
    }
    &:not(.active):hover {
      transform: scale(1.07);
    }

    @media (max-width: 800px) {
      height: 100%;
      width: 100px;
      margin-bottom: 0;
      padding-bottom: 0;
    }
    img {
      @include width-height(100%, 100%);
      object-fit: contain;
      max-width: 233px;

      @media (max-width: 800px) {
        width: 100%;
        height: 100%;
        max-width: 233px;
      }
    }
  }
  p {
    margin-top: 10px;
    margin-bottom: 0;
    @media (max-width: 800px) {
      margin-top: 0;
    }
  }
}

// Display only the title and photo until the card is clicked
.close.x,
p.name.active,
.wrap-texts-in-prev {
  display: none;
}

.name {
  color: $white;
  font-weight: bold;
  font-size: 1.3rem;
  @media (max-width: 800px) {
    font-size: 0.9rem;
  }
}

// *****************************************
// Complete style change
// When a card is assigned
// the "active" class
// *****************************************
@import '@/scss/cardOpen';
</style>

// src/features/app/components/card.tsx
import { $, component$, useSignal } from "@builder.io/qwik";
import type { MediaItem } from "../../../store/app.types";
import { useAppServices, useAppStore } from "../../../store/app-context";
import { VideoComp } from "./video-comp";
import "./card.scss";

export interface CardProps {
  obj: MediaItem;
}

const TMDB_IMAGE_BASE_URL = "https://image.tmdb.org/t/p/w342";
const DEFAULT_FLAGS = ["en", "it"] as const;
const FAVORITES_DEFAULT_PROFILE = "default";

const countWords = (str: string): number => str.trim().split(/\s+/).length;
const hasMoreThanWords = (str: string, n?: number): boolean => countWords(str) > (n || 60);
const getFirstWords = (str: string, n?: number): string =>
  str
    .split(/\s+/)
    .slice(0, n || 60)
    .join(" ");
const getRemainingText = (str: string, n?: number): string =>
  str
    .split(/\s+/)
    .slice(n || 60)
    .join(" ");
const findCutIndex = (str: string): number => str.search(/[.,]/);

function clipLongText(str: string, n?: number): string {
  if (!hasMoreThanWords(str, n)) {
    return str;
  }

  const firstPart = getFirstWords(str, n);
  const remainingText = getRemainingText(str, n);
  const cutIndex = findCutIndex(remainingText);

  if (cutIndex !== -1) {
    return `${firstPart}${remainingText.substring(0, cutIndex + 1)}...`;
  }

  return `${firstPart} ...`;
}

export const Card = component$((props: CardProps) => {
  const appStore = useAppStore();
  const services = useAppServices();
  const trailerKey = useSignal("");
  const open = useSignal(false);
  const showVideo = useSignal(false);

  const isFavorite = () => {
    const ids = appStore.state.favorites.idsByUser[FAVORITES_DEFAULT_PROFILE] ?? [];
    return ids.includes(props.obj.id);
  };

  const getTrailerData$ = $(async () => {
    const language = props.obj.kind === "movie" ? "it-IT" : "en-US";

    const key = await services.moviesApi
      .getTrailerKey({
        id: props.obj.id,
        kind: props.obj.kind,
        language,
      })
      .catch(() => null);

    trailerKey.value = key ?? "";
  });

  const onPlay$ = $(async () => {
    await getTrailerData$();
    showVideo.value = !showVideo.value;
  });

  const onToggleFavorite$ = $(() => {
    appStore.toggleFavorite(props.obj.id);
  });

  const posterUrl = props.obj.posterPath ? `${TMDB_IMAGE_BASE_URL}${props.obj.posterPath}` : "/src/assets/img/bigBrand.webp";
  const title = props.obj.title;
  const language = props.obj.language;
  const filledStars = Math.ceil((props.obj.voteAverage ?? 0) / 2);
  const remainingStars = 5 - filledStars;

  return (
    <div class={["bg-in-preview", open.value ? "active" : ""]}>
      <i class={["close", "x", "fas", "fa-times", open.value ? "active" : ""]} onClick$={() => (open.value = false)} />

      <div class={["wrap-texts-in-prev", open.value ? "active" : ""]}>
        <h1 class="name-in-preview">{title}</h1>

        <div class={["stars", open.value ? "active" : ""]}>
          {Array.from({ length: filledStars }).map((_, index) => (
            <i key={`star_full_${props.obj.id}_${index}`} class="fas fa-star" />
          ))}
          {Array.from({ length: remainingStars }).map((_, index) => (
            <i key={`star_empty_${props.obj.id}_${index}`} class="far fa-star" />
          ))}
        </div>

        <p class="overview">{clipLongText(props.obj.overview ?? "")}</p>
        <p class="releaseDate">release date: {props.obj.releaseDate ?? ""}</p>

        <div class={["original-lang", open.value ? "active" : ""]}>
          <span>Original lenguage:</span>
          {language && DEFAULT_FLAGS.includes(language as (typeof DEFAULT_FLAGS)[number]) ? (
            <img class="flag" src={`/src/assets/img/${language}.png`} alt={`${language} flag`} />
          ) : (
            <span>{language ?? ""}</span>
          )}
        </div>

        <button class="btn play" onClick$={onPlay$}>
          <i class="fas fa-play" />
        </button>

        {!isFavorite() ? (
          <h3 class="add-to-favourites" onClick$={onToggleFavorite$}>
            <i class="fas fa-plus" /> Add to favourites list
          </h3>
        ) : (
          <h3 class="remove add-to-favourites" onClick$={onToggleFavorite$}>
            <i class="fas fa-minus" /> Remove from favourites list
          </h3>
        )}

        {showVideo.value ? <VideoComp keyFromApi={trailerKey.value} obj={props.obj} onClose$={() => (showVideo.value = false)} /> : null}
      </div>

      <a
        class={["card", open.value ? "active" : ""]}
        href="#"
        onClick$={(event) => {
          event.preventDefault();
          open.value = true;
        }}
      >
        <div class={["poster", open.value ? "active" : ""]}>
          <div class={["img-wrap", open.value ? "active" : ""]}>
            <div class={["img-big", !props.obj.posterPath ? "place holder" : "", open.value ? "active" : ""]} style={{ backgroundImage: `url(${posterUrl})` }} />
            <img class={[open.value ? "active" : ""]} src={posterUrl} alt={`${title} sign poster`} />
          </div>
          <p class={["name", open.value ? "active" : ""]}>{clipLongText(title, 2)}</p>
        </div>
      </a>
    </div>
  );
});
